# Generated by Django 5.2.5 on 2025-09-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenitem',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, help_text='Precio al momento de la venta/servicio. Se autocompleta si se deja en blanco.', max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='agendamiento',
            unique_together={('vehiculo', 'fecha_hora_programada')},
        ),
    ]
