# Generated by Django 5.2.5 on 2025-09-10 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_ordenitem_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='chofer',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Chofer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to=settings.AUTH_USER_MODEL),
        ),
    ]
