# Generated by Django 5.2.5 on 2025-09-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_vehiculo_chofer'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamiento',
            name='fecha_hora_fin',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
